package com.waves.crm.settings.mapper;

import com.waves.crm.settings.domain.DicType;
import com.waves.crm.workbench.domain.Activity;

import java.util.List;
import java.util.Map;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sun Jul 03 22:32:12 GMT+08:00 2022
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sun Jul 03 22:32:12 GMT+08:00 2022
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sun Jul 03 22:32:12 GMT+08:00 2022
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sun Jul 03 22:32:12 GMT+08:00 2022
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sun Jul 03 22:32:12 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Sun Jul 03 22:32:12 GMT+08:00 2022
     */
    int updateByPrimaryKey(DicType record);

    List<DicType> selectAllDicType();

    int insertDicType(DicType dicType);

    int deleteDicTypeByCodes(String[] codes);

    int updateDicType(Map<String, Object> map);

    DicType selectDicTypeByCode(String code);

}